// Copyright (c) 2023, Eugene Gershnik
// SPDX-License-Identifier: GPL-3.0-or-later
             
// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.

#ifndef TRANSLIT_HEADER_TABLE_UZ_HPP_INCLUDED
#define TRANSLIT_HEADER_TABLE_UZ_HPP_INCLUDED

#include <Mapper/Mapper.hpp>

template<std::ranges::forward_range Range>
constexpr auto g_mapperUzDefault = makePrefixMapper<Range,
    Mapping{u'А', u"A"},
    Mapping{u'а', u"a"},
    Mapping{u'Б', u"B"},
    Mapping{u'б', u"b"},
    Mapping{u'В', u"V"},
    Mapping{u'в', u"v"},
    Mapping{u'Г', u"G"},
    Mapping{u'г', u"g"},
    Mapping{u'Ғ', u"G'"},
    Mapping{u'Ғ', u"G`"},
    Mapping{u'ғ', u"g'"},
    Mapping{u'ғ', u"g`"},
    Mapping{u'Д', u"D"},
    Mapping{u'д', u"d"},
    Mapping{u'Е', u"E"},
    Mapping{u'е', u"e"},
    Mapping{u'Ё', u"Yo"},
    Mapping{u'Ё', u"YO"},
    Mapping{u'ё', u"yo"},
    Mapping{u'Ж', u"J"},
    Mapping{u'ж', u"j"},
    Mapping{u'З', u"Z"},
    Mapping{u'з', u"z"},
    Mapping{u'И', u"I"},
    Mapping{u'и', u"i"},
    Mapping{u'Й', u"Y"},
    Mapping{u'й', u"y"},
    Mapping{u'К', u"K"},
    Mapping{u'к', u"k"},
    Mapping{u'Қ', u"Q"},
    Mapping{u'қ', u"q"},
    Mapping{u'Л', u"L"},
    Mapping{u'л', u"l"},
    Mapping{u'М', u"M"},
    Mapping{u'м', u"m"},
    Mapping{u'Н', u"N"},
    Mapping{u'н', u"n"},
    Mapping{u'О', u"O"},
    Mapping{u'о', u"o"},
    Mapping{u'П', u"P"},
    Mapping{u'п', u"p"},
    Mapping{u'Р', u"R"},
    Mapping{u'р', u"r"},
    Mapping{u'С', u"S"},
    Mapping{u'с', u"s"},
    Mapping{u'Т', u"T"},
    Mapping{u'т', u"t"},
    Mapping{u'У', u"U"},
    Mapping{u'у', u"u"},
    Mapping{u'Ў', u"O'"},
    Mapping{u'Ў', u"O`"},
    Mapping{u'ў', u"o'"},
    Mapping{u'ў', u"o`"},
    Mapping{u'Ф', u"F"},
    Mapping{u'ф', u"f"},
    Mapping{u'Х', u"X"},
    Mapping{u'х', u"x"},
    Mapping{u'Ҳ', u"H"},
    Mapping{u'ҳ', u"h"},
    Mapping{u'Ц', u"Ts"},
    Mapping{u'Ц', u"TS"},
    Mapping{u'ц', u"ts"},
    Mapping{u'Ч', u"Ch"},
    Mapping{u'Ч', u"CH"},
    Mapping{u'ч', u"ch"},
    Mapping{u'Ш', u"Sh"},
    Mapping{u'Ш', u"SH"},
    Mapping{u'ш', u"sh"},
    Mapping{u'Ъ', u"'"},
    Mapping{u'ъ', u"'"},
    Mapping{u'Э', u"Ee"},
    Mapping{u'Э', u"EE"},
    Mapping{u'э', u"ee"},
    Mapping{u'Ю', u"Yu"},
    Mapping{u'Ю', u"YU"},
    Mapping{u'ю', u"yu"},
    Mapping{u'Я', u"Ya"},
    Mapping{u'Я', u"YA"},
    Mapping{u'я', u"ya"}
>();

#endif
